### ISSUE TITLE
Fetch Error Can't load 

### ISSUE THREAD

**Issue by divyanshu-in** [deep-gaurav/MusicPiped#139]
on searching a song its giving me an error
![IMG_20201102_094354](https://user-images.githubusercontent.com/60056983/97829466-22697f00-1cf0-11eb-9be6-06c843aabe83.jpg)

**Comment by sainAk** [comment]
I think it's unable to soup links from the response
![IMG-20201102-WA0000](https://user-images.githubusercontent.com/46787056/97833017-4df16700-1cfa-11eb-9ac2-272dd1e81485.jpg)

**Comment by shom13** [comment]
Yeah, same here. Dont think the app is under active development as the last update was 11months ago. Just hope someone forks the app, as it used to be one of my favourites.

**Comment by pserran0** [comment]
Same here. No use for this app if it becomes discontinued. I hope someone forks the app.

**Comment by pserran0** [comment]
The app uses NewPipe Downloader. This might be the reason why it doesn't work. My NewPipe app is giving me a headache for the last 10 days.

**Comment by EliasKomar** [comment]
But it would probably be a lot of work to switch the downloader :/

**Comment by shom13** [comment]
But newpipe is working, i use it everyday. Every now and then youtube changes, hence newpipe too updates accordingly. Unfortunately for this app, there hasnt been an update in a long time, so the error.

**Comment by pserran0** [comment]
It doesn't work on my mobile device. It's been like this "Guru Meditation" error all the time. I'm used to it but it usually gets back after a few days... not this time. I'm starting to worry.

**Comment by shom13** [comment]
In that case i think you are running an older version, because it works on all of my devices running android 5 6 7 and 10. Try updating to ver 0.20.2

**Comment by pserran0** [comment]
> In that case i think you are running an older version, because it works on all of my devices running android 5 6 7 and 10. Try updating to ver 0.20.2

You're right. I'm running NewPipe 0.20.1. I'm using f-droid to update. Latest version on f-droid is 0.20.1. How can I update to 0.20.2?

**Comment by shom13** [comment]
Add newpipe upstream repo to your fdroid from settings. You'll get updates as and when its updated to github

https://newpipe.schabi.org/FAQ/tutorials/install-add-fdroid-repo/
