### ISSUE TITLE
Its fully broken, Youtube Changed stuff today (BUG)

### ISSUE THREAD

**Issue by PrivacyOsint2** [deep-gaurav/MusicPiped#146]
NewPipe has came out with an update with there NewPipe Extractor. Nothing will load until you update to the latest version.

Link:
https://github.com/TeamNewPipe/NewPipe/issues/7734

**Comment by mmaenz** [comment]
Fixed dependencies. New version is doing fine. Did a test just now!
It maybe needs some time for f-droid. You can grab a pre release here:   
https://github.com/mmaenz/MusicPiped/releases/tag/2.1.7

**Comment by PrivacyOsint2** [comment]
When will f-droid be updated?

**Comment by deep-gaurav** [comment]
@PrivacyOsint2  I've published a new release, F-Droid should update in a few days.
And I'm sorry I'm not currently working on this project, every update is thanks to contributions.
