### ISSUE TITLE
Feature request: Related video

### ISSUE THREAD

**Issue by faan11** [deep-gaurav/MusicPiped#16]
First of all thank you for your application. i have been finding it  really useful. Is it possible to enqueue all related videos when the user will select a new video?

**Comment by deep-gaurav** [comment]
If what you mean is Enqueing all videos that appear in search result for a query in app, then no currently it isn't possible but it seems like a good feature to be implemented, and not hard to do either, so can do it. :)

**Comment by qoheniac** [comment]
Would it be possible to follow YouTube's autoplay or do something similar?

**Comment by deep-gaurav** [comment]
Autoplay is tracked in #53 closing this as enqueing all search result has been implemented long back
