### ISSUE TITLE
Feature Request: Killing App

### ISSUE THREAD

**Issue by Derebeyi** [deep-gaurav/MusicPiped#17]
Greetings,

I'm using Android 6.0 on LG G3. Whenever I quit, app stays on notification bar just like a music player. This is usefull however I can't truly close the app. Clearing 'task manager' doesn't help. Only force stopping from settings seems to work. A quit option in app will be very good.

Thanks.

**Comment by deep-gaurav** [comment]
There is that close button in the notification, it is supposed to kill app both process and service? Have you tried it?

**Comment by Derebeyi** [comment]
Okay I found it.I didn't see that before as it was a white X mark on a white background.I couldn't find if didn't know where to look.Is this something to do with my theme or dev's styling decision?

**Comment by deep-gaurav** [comment]
Ideally it should look like this, 
![screenshot_20181101_070443](https://user-images.githubusercontent.com/28472450/47815523-95913100-dd76-11e8-867f-c60915a08d95.png)

If it doesn't it could be the device theme,

**Comment by Derebeyi** [comment]
![issue](https://user-images.githubusercontent.com/6437707/47823485-94adce80-dd79-11e8-8dee-6cb85950afe9.png)

**Comment by deep-gaurav** [comment]
new app uses custom icons, so it should be fixed, closing issue
