### ISSUE TITLE
no Permissions on android Pie

### ISSUE THREAD

**Issue by machiav3lli** [deep-gaurav/MusicPiped#19]
![screenshot_musicpiped_20181102-144215](https://user-images.githubusercontent.com/40302595/47918732-b3ad7d00-dead-11e8-99cf-8d0c69fe24ca.png)
![screenshot_einstellungen_20181102-144249](https://user-images.githubusercontent.com/40302595/47918733-b4461380-dead-11e8-8017-e5682f542ca6.png)

as to be seen, the app isn't asking for any permissions on Android Pie, compared to Newpipe which takes storage permission, and so it's not working.

**Comment by deep-gaurav** [comment]
The app does not need storage permission at all, it does not play local music in your phone so does not need storage permission.
Use search on top left to search for any music on YouTube

**Comment by deep-gaurav** [comment]
Closing issue then,
And good luck
