### ISSUE TITLE
Add Screenshots

### ISSUE THREAD

**Issue by deep-gaurav** [deep-gaurav/MusicPiped#2]
Some Screenshots

![screenshot from 2018-10-02 23-42-18](https://user-images.githubusercontent.com/28472450/46368113-03293f00-c69d-11e8-9130-b10bfe55e2c0.png)
![screenshot from 2018-10-02 23-43-15](https://user-images.githubusercontent.com/28472450/46368115-03293f00-c69d-11e8-81a9-776f498b0e02.png)

**Comment by deep-gaurav** [comment]
Version 0.1.2-beta

![screenshot_20181016_222507](https://user-images.githubusercontent.com/28472450/47061255-54cddf80-d1ee-11e8-8005-cf612cd9f09c.png)
![screenshot_20181016_222800](https://user-images.githubusercontent.com/28472450/47061256-54cddf80-d1ee-11e8-8dd8-051ce9f928cd.png)
![screenshot_20181016_222839](https://user-images.githubusercontent.com/28472450/47061257-55667600-d1ee-11e8-92ce-16ef119d1554.png)
![screenshot_20181016_223403](https://user-images.githubusercontent.com/28472450/47061259-55667600-d1ee-11e8-9c2d-7b5217f33243.png)
![screenshot_20181016_223451](https://user-images.githubusercontent.com/28472450/47061260-55667600-d1ee-11e8-8d86-a1e57bc2acb1.png)
![screenshot_20181016_223510](https://user-images.githubusercontent.com/28472450/47061261-55ff0c80-d1ee-11e8-89ef-5aa7a28686cd.png)
![screenshot_20181016_223531](https://user-images.githubusercontent.com/28472450/47061262-5697a300-d1ee-11e8-8738-ae03d618e89d.png)
![Uploading Screenshot_20181016_231332.png…]()

**Comment by deep-gaurav** [comment]
Screenshots for v1.0.0+
(ignore ads for F-Droid version)

![nexus 6p-screenshot1](https://user-images.githubusercontent.com/28472450/50723381-f6d0da00-1102-11e9-93e6-a12c845975a2.png)
![nexus 6p-screenshot2](https://user-images.githubusercontent.com/28472450/50723382-f6d0da00-1102-11e9-8155-4f6fe2798116.png)
![nexus 6p-screenshot3](https://user-images.githubusercontent.com/28472450/50723383-f6d0da00-1102-11e9-8650-422b365c9f66.png)
![nexus 6p-screenshot4](https://user-images.githubusercontent.com/28472450/50723384-f7697080-1102-11e9-8913-6e96540de850.png)
![nexus 6p-screenshot5](https://user-images.githubusercontent.com/28472450/50723385-f7697080-1102-11e9-9dcd-582d7d4ee66b.png)

**Comment by deep-gaurav** [comment]
Current screenshot shows ads, which isn't case anymore and might repel some people, they need to be changed with new/better screenshot, and if possible add in F-Droid since I don't know how to do that, help would be appreciated., 

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

Some help can be found here

**Comment by deep-gaurav** [comment]
Screenshots will need update with v1.1

**Comment by Poussinou** [comment]
Hi, F-Droid contributor here.

To add the screenshots, just follow [this guide](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository). We prefer to host the screenshots in the original source repo. The fdroiddata repo is already too big.

Basically, you can add a fastlane directory at the root of your repo. Just follow the example of [Newpipe](https://github.com/TeamNewPipe/NewPipe). As you can see, you can also directly add the descriptions, and a changelog that will be shown directly on [F-Droid website like this one](https://f-droid.org/packages/de.k3b.android.toGoZip/) and in the client.

Please be sure to do that before tagging the next release, so that screenshots can appear with the next update that our bot will build.

**Comment by Poussinou** [comment]
Totally off-topic, but your app actually violates the terms of conditions of Google Play, because it allows to stream audio from youtube without using the app or something else, and because you can close your phone and still have the audio (coming from youtube) in the background. You can get a strike for that if Google find your app, just to let you know...

**Comment by deep-gaurav** [comment]
@Poussinou Thanks for help,. 

And regarding play store, I'm aware of it and actually Google too, they blocked my Adsense account and do not allow me to update app, I wish to remove ad from that version but can't since Google is rejecting updates. It's still better then complete ban atleast I try to redirect PPL from play store to F-Droid.

**Comment by Poussinou** [comment]
How, I thought Google wouldn't let the app online. Looks very weird, but ok...

Obviously your app is welcome at F-Droid, and I personally use it a lot :)

**Comment by deep-gaurav** [comment]
Btw, out of context, but it has been ~3 days since I posted last update which was kind of major and had many fixes,. It doesn't seem to be updated on F-Droid yet

**Comment by Poussinou** [comment]
As you can see [here](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/deep.ryd.rydplayer.yml), our bot knows there is an update, but it's not build yet, or not yet signed. We lack some humans at F-Droid to speed up things. I hope it should appear today or tomorrow.

**Comment by deep-gaurav** [comment]
Ok got it thanks, I didn't knew how long it generally takes to update on
F-Droid.

Also can you confirm what flutter branch is being used by F-Droid build
bots, stable or master

**Comment by Poussinou** [comment]
It usually takes a few days

I assume we use stable version, as you can see in the metadate file `srclibs:
      - flutter@v1.2.1
`

@rudloff can you confirm?

**Comment by Rudloff** [comment]
Yes, we currently use Flutter 1.2.1 for this app. If new versions require another Flutter version, we will have to update the metadata.

However, 1.1 [failed to build](https://f-droid.org/wiki/page/deep.ryd.rydplayer/lastbuild_39) because Flutter does not like the version name.

**Comment by deep-gaurav** [comment]
Updated the version for flutters liking and drafted release, hopefully it builds 

The problem is that my device got stolen recently and current one is a very old device which doesn't even recognise PC.

So only way for me to work is use AVD, which doesn't support flutter release since it's ARM only. and debug version doesn't translate well to release.

**Comment by deep-gaurav** [comment]
@Poussinou I added screenshots following NewPipe pattern in fastlane hierarchy in root folder. Will there need to be changes in fdroiddata to reflect it or will it auto update. 

Also is it possible to add donation link in fdroiddata. `https://github.com/deep-gaurav/MusicPiped#donate` will be nice enough as website no longer exist, since I dont have domain anymore.

It would also be great if website link can be removed from fdroidentry for aforementioned reason
