### ISSUE TITLE
[Feature Request] Scrobbling support (Last.fm, etc)

### ISSUE THREAD

**Issue by regagain** [deep-gaurav/MusicPiped#21]
Hi!

It would be great if MusicPiped could scrobble to Last.FM / etc. 

One way to achieve that is by sending broadcast status to Simple Last.fm Scrobbler. See documentation: https://github.com/tgwizard/sls/blob/master/Developer%27s%20API.md

**Comment by deep-gaurav** [comment]
Not exactly sure what scrobbling is, but will try to implement it.

**Comment by regagain** [comment]
Thanks! Scrobbling consists in sending metadata of the track being played to a server (for example Last.FM) to build a profile of the user's musical taste. This data can then be used to, for example, recommend other artists. See https://en.m.wikipedia.org/wiki/Last.fm#Scrobbling

**Comment by deep-gaurav** [comment]
Hi, 
Initial scrolling support has been implemented in latest version, you'll get update of fdroid soon or get apk from release page or website to test (they've ads)

Scrolling may not work like other app though, since it track name is video name of YouTube and artist is uploader of YouTube video, these may not match what is on last.fm.

**Comment by regagain** [comment]
Thank you! Works well.
For more correct artist/track name retrieval, maybe it's worth looking at how [web scrobbler](https://github.com/web-scrobbler/web-scrobbler) does it.

**Comment by nestarz** [comment]
How to activate scrobbling in the latest update 0.2.3beta ? Also many thanks for your efforts !

**Comment by john3voltas** [comment]
@deep-gaurav 
It's not working on my phone but I thinks it's something wrong with SimpleLastFM scrobbler and not with MusicPiped.
Anyway, I just wanted to thank you (a lot) for having implemented scrobbling.
Cheers

**Comment by john3voltas** [comment]
@deep-gaurav 
It's working here.
I guess you can close this issue.
Thanks a bunch.
Cheers

**Comment by deep-gaurav** [comment]
Thanks for letting me know
