### ISSUE TITLE
Playlist shuffle play option not visible

### ISSUE THREAD

**Issue by Harizio2** [deep-gaurav/MusicPiped#26]
I can't find the option for shuffle play anywhere. I'm assuming it should be here, but nothing shows up:
![image](https://user-images.githubusercontent.com/43677902/49091187-f7ef2b80-f267-11e8-96ba-a73f7f0c94b4.png)
Phone: Huawei p10 lite
Model: WAS-LX1
Android: 8.0.0.

**Comment by deep-gaurav** [comment]
Sorry no option available right now, will be added in next version, You can enable shuffle for current queue in player though

**Comment by Harizio2** [comment]
Oh my bad I didn't notice you can pull up the player options from the bottom 😅

**Comment by deep-gaurav** [comment]
The UI is currently not best, can get confusion at start 😅.

Closing this issue
