### ISSUE TITLE
[UX Suggestion] Unify swiping between tabs

### ISSUE THREAD

**Issue by Harizio2** [deep-gaurav/MusicPiped#27]
Removing tracks when swiping left or right in the "tracks" tab is a bit confusing because the same swipe can be used to switch tabs in all the other tabs (home, artists, playlists).

**Comment by deep-gaurav** [comment]
App is being remade in Flutter with much better UI, and this is fixed in it

**Comment by deep-gaurav** [comment]
App is updated, and it's now done i think, so closing issue
