### ISSUE TITLE
Music starts playing automatically + app running in the background even if I dont want to

### ISSUE THREAD

**Issue by RaidenHUN** [deep-gaurav/MusicPiped#29]
There's no settings for this but even after I quit, stop the app when I plug in my jack the music just starts playing. It is very annyoing, also means that the app is running in the background even if I shut it off or "kill" it.

**Comment by RaidenHUN** [comment]
Oh, what I forgott:
I am using LG V30 on Oreo. Just stock ROM, no custom.

**Comment by RaidenHUN** [comment]
> There is a cross button in notification after next button, it kills app. Also try disabling respect audio focus in settings. It should prevent it from starting automatically on getting audio focus

I do not have any notification. 
It simply plays the music in the background, so I dont have a noti in the statusbar/ notification (pulldown) screen. 
If I disable "Respect Audio Focus", wouldnt that casuse an issue when I receive a call, like the music wont stop playing?

**Comment by RaidenHUN** [comment]
I also want to add an addition to my original comment.
The music doenst start right away when I plug in the jack, it start playing when I go into YT app (Youtube Vanced), or PowerAMP.
Kind of weird.

**Comment by deep-gaurav** [comment]
You do not have notification? That's wierd, can you check notification channels in app info, is it being blocked? 
Audio focus is broken, so it's either on or off.. sorry for that.
A completely revamped version is under progress these are fixed in it. Will take a week or two for it to release..

**Comment by RaidenHUN** [comment]
Yeah, I checked it , it was enabled but "My Backup Service" wasnt. No there's notification.
Though it's weird, I havent met an app that needed specially enable anything to get notification it usually the other way around I have to disable stuff to get rid of annyoing or unessesary notifications. 

SO now there's noti, BUT if I go into Youtube and start playing a video and I stop the video, the music from MusicPiped starts to play. And sometimes if I go to YT it starts to play - sometimes. 
It's deffinitely doesnt like YT /YT Vanced app. :D

**Comment by deep-gaurav** [comment]
Are you sure you're using latest version? Notification doesn't seem to have cross button which should be there.

**Comment by deep-gaurav** [comment]
Check issue #17

**Comment by deep-gaurav** [comment]
I use inbuilt Android icons in notification to maintain customisability with themes. But it seems like your phone doesn't have the close icon, so it's not showing. I've no idea why notification was blocked in your device. Never happened with anyone else.

I'll give you another apk in some time which will use inbuilt icon for close. It'll show up then

**Comment by RaidenHUN** [comment]
Yeah, it seems like I have the X button, but it's white, so I'm not able to see it.
Still the original issue still exist with the interation of youtube.

**Comment by deep-gaurav** [comment]
Audio focus and icons should be now fixed, closing issue, reopen if it persists
