### ISSUE TITLE
Any plans for desktop Linux?

### ISSUE THREAD

**Issue by tiotrom** [deep-gaurav/MusicPiped#31]
I do not think there is an alternative to this fir Linux desktop. Any possibility of creating one version for that too? Thanks!

**Comment by ArmeF97** [comment]
Have you ever tried Anbox?

**Comment by deep-gaurav** [comment]
![screenshot_2018-12-12_09-40-30](https://user-images.githubusercontent.com/28472450/49847117-80d39e80-fdf4-11e8-827f-f3e19c8c94e2.png)

Tested, with some tweaks got app to run, and search works. No playback ofcourse will need further changes

**Comment by tiotrom** [comment]
Oh that sounds exciting! Thank you!

**Comment by deep-gaurav** [comment]
https://drive.google.com/open?id=130sfBtljlstbQjCfP_CDVo8WGy6DXa00

Test this appImage

**Comment by tiotrom** [comment]
@deep-gaurav In Manjaro linux nothing happens. I am familiar with appimages but cannot make this one do anything.

**Comment by probonopd** [comment]
`libjsoncpp.so.1` needs to be bundled inside the AppImage then.

**Comment by deep-gaurav** [comment]
I'm not familiar with desktop development so yeah possibly missed it and maybe some other libs, I'll bundle it

**Comment by probonopd** [comment]
How do you produce the AppImage? There are tools that may help...

**Comment by deep-gaurav** [comment]
This is process I follow 
I compile project with flutter-desktop-embedding(https://github.com/google/flutter-desktop-embedding) example,
It gives a binary with a data directory containing some libs and compiled flutter project directory (assets),
I then make an AppDir directory put compiled files and assets along with an mplayer(that is what i used for playback) binary in /urs/bin in App dir, and also copy those libs in /usr/lib, 
then use appimagekit to produce appimage binary..

**Comment by deep-gaurav** [comment]
I'll upload this flutter project as a new repo soon(have a lot of clearance to do),

I dont know what external libs flutter binary depended so didnt copied any except what was produced, also there can be missing libs for mplayer if mplayer has dependencies.,

**Comment by deep-gaurav** [comment]
![image](https://user-images.githubusercontent.com/28472450/50728974-fe6e9e00-1157-11e9-8c2d-93b4ce8fd68c.png)

That was my mistake, i think i need to add these dependencies, (https://github.com/google/flutter-desktop-embedding/blob/master/library/README.md)

**Comment by deep-gaurav** [comment]
There is a working model available, but I lack experience to package it into a working AppImage or other package system, Any help would be appreciated on packaging for desktop

**Comment by mlaradji** [comment]
Hi @deep-gaurav. Thank you for your efforts.

By working model, do you mean that you were able to compile a working Linux binary? If so, could you kindly provide me with the build instructions? I would like to work on packaging it into a `deb` or a `snap`.

**Comment by deep-gaurav** [comment]
Hi @mlaradji ,

Try this zip.
https://drive.google.com/file/d/1-CLwL1jdzMR4u78oh1pse6jblD8EspLv/view?usp=sharing

Running main should run app, but it uses mplayer to play audio. therefore mplayer is a dependency right now.

This is made using https://github.com/Drakirus/go-flutter-desktop-embedder I'll create a separate repo for this later if it works. Thanks

**Comment by mlaradji** [comment]
Running `main` results in the error:
```
2019/02/12 19:31:10 stat /home/deep/go-flutter-desktop-embedder/example/music_piped/flutter_project/music_piped/build/flutter_assets: no such file or directory
```

Is the directory hard-coded into the executable? I was unable to find the path in any configuration file.

**Comment by deep-gaurav** [comment]
Hmm, that's strange it should not have been hard-coded, I'll create a separate repo for it and will fix there

**Comment by deep-gaurav** [comment]
@tiotrom 
This is a highly work in progress but try this
http://deep-gaurav.github.io

**Comment by deep-gaurav** [comment]
Web version is functional so i think this is also done, raise issue in web repo if encounter problem
https://github.com/deep-gaurav/musicpiped_web
