### ISSUE TITLE
Video playing support as option

### ISSUE THREAD

**Issue by DI555** [deep-gaurav/MusicPiped#32]
As we downloading full stream with video... and decoding it anyway... and the core decompresses it anyway...,
please add as option the support of playing video also! It would be great! And could be switch off of course.
Many thanks in advance!

**Comment by deep-gaurav** [comment]
Umm, no it does not download video stream, just audio stream, so that option wont be added.
but you might want to look at newpipe
https://github.com/TeamNewPipe/NewPipe

**Comment by DI555** [comment]
Anyway, would be great if MP someday supports video.., because any played position has and video stream too! And core of MP has possibility to decodong video , as described in manuals...
So I mean during listening to music may be get wanting to see that video too, here now, in the MP!

**Comment by deep-gaurav** [comment]
Media player does have capability but main aim of this app is to be a music player and there are lots of stuffs to fix right now, so that will not be a priority. Could be added in later version
