### ISSUE TITLE
NOTHING PLAYING, but something IS playing

### ISSUE THREAD

**Issue by ArmeF97** [deep-gaurav/MusicPiped#34]
![immagine](https://user-images.githubusercontent.com/6240983/50725095-a5235200-10f8-11e9-9ce9-7bc388559a8c.png)

But something was playing...

**Comment by deep-gaurav** [comment]
does it persist? it can happen when android system's broadcast fails. You can try to clear it from recent (not remove notification) and reopen app.
this should fix it

**Comment by deep-gaurav** [comment]
Will add some workarounds in next version

**Comment by ArmeF97** [comment]
It doesn't persist. Only sometimes

**Comment by deep-gaurav** [comment]
This issue is fixed i think so closing
