### ISSUE TITLE
White space in home

### ISSUE THREAD

**Issue by ArmeF97** [deep-gaurav/MusicPiped#35]
Is it alright? Shouldn't it be removed?
![screenshot_20190108-230409_musicpiped](https://user-images.githubusercontent.com/6240983/50861763-f736d280-1399-11e9-877c-9b8f4b23b86f.png)

**Comment by deep-gaurav** [comment]
That is actually space for ad, I do not control it.. When no ad is available, it's white space.. Fdroid version for eg does not have ad so that space isn't there either.

I will try to size it to 0 when ad isn't available

**Comment by deep-gaurav** [comment]
Play store version is now deprecated as google does not allow updating, upgrade to FDroid version, it doesnt have ads nor the blank space :)
