### ISSUE TITLE
fix decrypt error

### ISSUE THREAD

**Issue by theScrabi** [deep-gaurav/MusicPiped#36]
Jo @deep-gaurav, due to the shutdown you need to update the extractor to this commit here:
https://github.com/TeamNewPipe/NewPipeExtractor/commit/99915e4527c0a7ea264f952c182871b73f7bbbe8

**Comment by deep-gaurav** [comment]
Thanx for letting me know,
But how do I update extractor? I was using maven repo. So I think gradle was including it, can I edit it?
I don't see a version update of extractor

**Comment by theScrabi** [comment]
Yes, you may just replace the id of the commit. Like described here:
https://teamnewpipe.github.io/documentation/04_Run_changes_in_App/#run-your-changes-on-the-extractor

**Comment by deep-gaurav** [comment]
1a6c787 fixes it Thanks
