### ISSUE TITLE
Song in permanent loop not working

### ISSUE THREAD

**Issue by FlexW** [deep-gaurav/MusicPiped#38]
The button for playing a song in a permanent loop does not work.
Steps to reproduce:
1. Search a song.
2. Play the song.
3. Open the detailed song view and press the loop button.
4. Let the song play to the end and then the song will not play again.

I'm using the version 1.0.2 from f-droid.

**Comment by deep-gaurav** [comment]
Thanks for reporting, will fix in next version

**Comment by deep-gaurav** [comment]
Same as #41  Should now be fixed, reopen if persists
