### ISSUE TITLE
Following sound does not play automatically

### ISSUE THREAD

**Issue by Norde** [deep-gaurav/MusicPiped#41]
At the end of a track, the transition to the next song is done correctly but the playback does not start/restart.
This occurs either the playback mode is set to "repeat all" or "repeat only this song".

Also the shuffle mode does not seem to work.

This is probably the same problem as #38

**Comment by deep-gaurav** [comment]
1a6c787  fixes issue new version released, FDroid will update soon

**Comment by Norde** [comment]
Thanks a lot !
