### ISSUE TITLE
Crash when reopening app

### ISSUE THREAD

**Issue by deep-gaurav** [deep-gaurav/MusicPiped#45]
App will crash if opened again after closinf and played. Clearing data allows to use again, but subsequent opening will crash. Regression from last update.

Will fix ASAP

**Comment by deep-gaurav** [comment]
69feefb fixes this issue

**Comment by ArmeF97** [comment]
may I suggest to do a separated commit when you upgrade the version number?

**Comment by deep-gaurav** [comment]
Version is updated in separated commit generally, this was only fix I did so included in same, and messed with it too in same 😅,

But thanx for suggestion, I'll make it a practice from now.
