### ISSUE TITLE
Still playing songs when i get and receive call

### ISSUE THREAD

**Issue by A5TR1K** [deep-gaurav/MusicPiped#46]
App keeps playing song when i get a call along side of ringtone and when i receive it this it keeps playing in the other speaker. Desired behaviour should be, when i get and  receive a call it should pause automatically and when i reject or end my call it should resume again.

**Comment by deep-gaurav** [comment]
There is some problem with audio focus also reason for crashes , I'm working on fixing it. Thanks for reporting

**Comment by deep-gaurav** [comment]
7bd3183 should fix it, new version released, if not fixed in v1.0.7 reopen issue
