### ISSUE TITLE
Adding song to queue doesn't work from search menu

### ISSUE THREAD

**Issue by Norde** [deep-gaurav/MusicPiped#47]
The option to add a song from search result to current queue doesn't work.
(ie +/+ button appearing during a long press on a song in search result).

Music Pipe shows the processing icon but it end without any change.

Also same bug occur when adding multiple song to current queue but processing state never end.

**Comment by deep-gaurav** [comment]
Can you tell which version you are using?

**Comment by Norde** [comment]
This bug happened under 1.02 (F-droid version).

It also happening with latest version (1.06).

**Comment by deep-gaurav** [comment]
I think it has been fixed so closing, if it still exists please reopen

**Comment by Norde** [comment]
It works perfectly (including when adding multiple tracks simultaneously).

Thanks a lot Deep-gaurav :)
