### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by wikd** [deep-gaurav/MusicPiped#48]
Is there any way to get the song title to show in the notification instead of the channel name? Apps like quicklyric cannot find the song because of that.

**Comment by deep-gaurav** [comment]
Can you point out a open source music player app with which it works? I can study it's notification style to match it

**Comment by dimqua** [comment]
Vanilla Music, for example.

**Comment by wikd** [comment]
[https://play.google.com/store/apps/details?id=com.poupa.vinylmusicplayer](url)

**Comment by deep-gaurav** [comment]
It uses built in notification layout so i think it'll work now, closing issue, reopen if it's not solved
