### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by vit1-irk** [deep-gaurav/MusicPiped#49]
OS: Android 9.0 Pie

Installed your app and tried to make a search for favorite youtubers to watch some music of them. When typing a query, search suggestions do work, but the search results do not appear, just progress drawer is rotating
![screenshot_20190218-215621](https://user-images.githubusercontent.com/3207316/52965075-efc60880-33de-11e9-92ec-a9bfc1f2543a.png)

**Comment by deep-gaurav** [comment]
Thanks for reporting I'll look into it,

**Comment by vit1-irk** [comment]
I have noticed, that if I use cellular data, it works perfectly.

But when the network is delivered using wifi, search stops working like this.

**Comment by vit1-irk** [comment]
Problem is "resolved". MusicPiped doesn't fetch search results from YouTube itself as NewPipe does, it uses Invidio.us which is blocked in Russia by roskomnadzor

I don't know what to do in this situation, it is up to you. But if you won't fix this issue it is worth mentioning in help screen or at startup that user must use proxy or VPN to access the app.

The other solution is to allow setting your own address to reach the API for videos

**Comment by deep-gaurav** [comment]
Newpipe does not use invidious but instead I use invidious to fetch search results.
I didn't knew it was blocked in Russia,
NewPipe can't be blocked since it is webscrapper working in the app itself and does not connect to any other site except YouTube.

I think I can give an option to select backend, i.e NewPipe or Invidious.
Both are not equal in features

**Comment by vit1-irk** [comment]
There are several Invidious instances which are not yet blocked in Russia. It is possible to let users choose the search backend and to type their own address if it is possible.

**Comment by DI555** [comment]
> I think I can give an option to select backend

It would be great!

**Comment by vit1-irk** [comment]
The problem still remains, after many updates
Please do something

Using the player through VPN is possible and it works, but not everyone runs VPN full-time on the device

**Comment by deep-gaurav** [comment]
Sorry for such a long delay. Selection of Invidious instance will be provided in settings as of version v1.1.5, Closing issue, reopen if it does not work.
