### ISSUE TITLE
Strange error during startup

### ISSUE THREAD

**Issue by vit1-irk** [deep-gaurav/MusicPiped#50]
See the previous issue, and that's the another error

![screenshot_20190218-214448](https://user-images.githubusercontent.com/3207316/52965499-ee491000-33df-11e9-8dd2-eb393dd05ab1.png)

**Comment by deep-gaurav** [comment]
Can you describe a situation when this happens?

**Comment by vit1-irk** [comment]
It happened after I have installed the app and wasn't able to turn on any of the videos. I swiped this thing "not playing" and swiped left-right on the background above "nothing playing"

**Comment by deep-gaurav** [comment]
Player has been redone and it's been fixed.
