### ISSUE TITLE
Songs added in version 1.0.2 crash 1.0.6

### ISSUE THREAD

**Issue by esmoak** [deep-gaurav/MusicPiped#51]
On Huawei device running stock android 8.0.0.

1.0.6 crashes when attempting to play tracks already in the program from 1.0.2. 

New tracks can be searched and played. 

Solution seems to be to delete the old tracks and re-add, then they work correctly.

**Comment by deep-gaurav** [comment]
It's a regression in new version, I'll fix it ASAP

**Comment by deep-gaurav** [comment]
ca408df should fix this, new version released, if error persists reopen issue
