### ISSUE TITLE
Large playlist

### ISSUE THREAD

**Issue by wikd** [deep-gaurav/MusicPiped#52]
If you load a huge Playlist it causes all kinds of massive issues lol,takes forever to load and switch songs and if you try to shuffle them it will just crash most times. I really hope these issues get worked out because this is shaping up to be a really great app.

**Comment by deep-gaurav** [comment]
There is no handling of error if it occurs at time of load, therefore if any music fails to load it keeps on loading. I think also cause of #47 
Secondly the playback screen and queue is not implemented properly which does needs to be reimplemented.

But what shuffle are you talk about, shuffle at home which returns a new playlist or shuffle in playback screen?

**Comment by deep-gaurav** [comment]
Playback screen was first thing I reimplemented in flutter, and was not really aware of all the mechanics. So there r some really bad programming practices in there which causes issues and will be reimplemented

**Comment by deep-gaurav** [comment]
Playback Screen was already redone, but still a lot of unnecessary syncing were happening which caused issues with big playlists,.. as of v1.2.0, lots of optimizations have been done and should now be able to handle huge playlists (I tried 200+ long queue on my device which is really old subpar device, still handled quite well)
