### ISSUE TITLE
Auto playlist based on YouTube suggestion.

### ISSUE THREAD

**Issue by ugaugabuga** [deep-gaurav/MusicPiped#53]
After playing a song MusicPiped should play other songs suggested by YouTube automatically.

**Comment by deep-gaurav** [comment]
The app was designed to be a normal music player where music is just fetched from youtube.

That could be added as an additional feature though.

**Comment by deep-gaurav** [comment]
It's finally added open a track/search and play it and open playerscreen and tap the sync shaped icon to enable autoplay
