### ISSUE TITLE
[feature request] higher resolution for play notification icons

### ISSUE THREAD

**Issue by arkhub** [deep-gaurav/MusicPiped#56]
Is it possible to add more specific icons for high resolution display? currently the icon in notifications (play, stop, etc) are a bit blurred, thank you.

**Comment by arkhub** [comment]
ok, thank you.

**Comment by deep-gaurav** [comment]
Let it be open till it's fixed as a reminder

**Comment by deep-gaurav** [comment]
From v1.1 app will use System Icons so should scale with display. Reopen if issue persists
