### ISSUE TITLE
Android Studio build failed

### ISSUE THREAD

**Issue by 1emirozdemir** [deep-gaurav/MusicPiped#57]
![youtube hata](https://user-images.githubusercontent.com/35995145/53769343-ab615f00-3eec-11e9-8851-8f9233032a08.png)
ERROR
`Flutter SDK not found. Define location with flutter.sdk in the local.properties file.

Please help me I don't use Flutter at after. I've never used a flutter before
`

**Comment by deep-gaurav** [comment]
This app is made in flutter you've to follow guide on https://flutter.io to set up flutter first

**Comment by deep-gaurav** [comment]
Basically download flutter SDK, extract it and add bin folder in your PATH variable

**Comment by 1emirozdemir** [comment]
Thank you i have successfully installed sdk but get this error `Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
` Please help me!

**Comment by deep-gaurav** [comment]
Sorry for late reply,
but it looks like flutter is not returning OK, 
Can you run `flutter doctor` ?

**Comment by deep-gaurav** [comment]
Android studio can compile it with flutter, refer to flutter.dev for instructions. Closing this issue
