### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by warlockers** [deep-gaurav/MusicPiped#58]
Hey guys, fresh install, MIUI v8 Android 6 based. Aplication crash after launch.

**Comment by deep-gaurav** [comment]
Is it possible for you to get crashlog?
I've noticed some crash issues but need log to analyse it

**Comment by warlockers** [comment]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/santoni/santoni:6.0.1/MMB29M/V8.2.9.0.MAMMIEA:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 19170, tid: 19170, name: p.ryd.rydplayer  >>> deep.ryd.rydplayer <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/common/switches.cc(133)] Check failed: mapping && size. Unable to resolve symbols: _binary_icudtl_dat
'
    r0 00000000  r1 00004ae2  r2 00000006  r3 f74d5b7c
    r4 f74d5b84  r5 f74d5b34  r6 00000002  r7 0000010c
    r8 ffc21ab4  r9 00000000  sl ffc224c8  fp ab317558
    ip 00000006  sp ffc21970  lr f7253f5d  pc f7256358  cpsr 400f0010

backtrace:
    #00 pc 00044358  /system/lib/libc.so (tgkill+12)
    #01 pc 00041f59  /system/lib/libc.so (pthread_kill+32)
    #02 pc 0001ba6f  /system/lib/libc.so (raise+10)
    #03 pc 00018c11  /system/lib/libc.so (__libc_android_abort+34)
    #04 pc 000167d0  /system/lib/libc.so (abort+4)
    #05 pc 001344f7  /data/app/deep.ryd.rydplayer-1/lib/arm/libflutter.so (offset 0x111000)
    #06 pc 0015ca4b  /data/app/deep.ryd.rydplayer-1/lib/arm/libflutter.so (offset 0x111000)
    #07 pc 0015038d  /data/app/deep.ryd.rydplayer-1/lib/arm/libflutter.so (offset 0x111000)
    #08 pc 0015c0fd  /data/app/deep.ryd.rydplayer-1/lib/arm/libflutter.so (offset 0x111000)
    #09 pc 001e1aa9  /data/app/deep.ryd.rydplayer-1/lib/arm/libflutter.so (offset 0x111000)
    #10 pc 0015b3d1  /data/app/deep.ryd.rydplayer-1/lib/arm/libflutter.so (offset 0x111000)
    #11 pc 0012b76b  /data/app/deep.ryd.rydplayer-1/lib/arm/libflutter.so (offset 0x111000)
    #12 pc 007bdffd  /data/app/deep.ryd.rydplayer-1/oat/arm/base.odex (offset 0x63c000)

**Comment by deep-gaurav** [comment]
There had been many updates to app since then and with flutter itself I assume it no longer happens and so closing issue. If it still occurs, please reopen it
