### ISSUE TITLE
Erratic playback

### ISSUE THREAD

**Issue by maszek** [deep-gaurav/MusicPiped#59]
This player is a great idea which has the potential to save loads of data being downloaded unnecessarily. Alas, it rarely does what I want it to do. 
1. Halfway songs, the player slips to previous songs I've played or looked up.
2. I cannot inlfuece the list of previous songs played on.
3. It only plays one song a the time of songs from imported playlists. I have to press play after eacht song on the playlist.
4. It does not import special characters, which are being replaced by coded characters (some kind of ASCII)
5. I cannot delete created or imported playlists.
So, in effect, I've deleted the app. I'll check later for better versions.

**Comment by deep-gaurav** [comment]
Are you sure you're on latest version from F-Droid and not play store.
Many of listed features are fixed

**Comment by deep-gaurav** [comment]
Importantly,
3,4,5, have been fixed

3 still occurs is playback is affected by some other app, it'll be fixed in next version completely

I'm not exactly sure what you mean by 1 and 2,

**Comment by letkan** [comment]
Today I experienced 1. myself except that half way through the song it jumped to next in a list of 3 songs.
Occasionally when I start a song it plays for a few seconds and then it stops for some seconds and starts again. This one is not related to network, I experienced it on wifi and data as well. I'll try to get a logcat.

**Comment by deep-gaurav** [comment]
Is it reproducible?
Looks to me like bad cache., I'll add option to remove cache of individual tracks,.

**Comment by letkan** [comment]
> Is it reproducible?
It' random.
is this meaningful in any way?
`MediaPlayer: Error (-38,0)
MediaPlayerNative: Attempt to call getDuration in wrong state: mPlayer=0x75222b94c0, mCurrentState=0`
from logcat.

**Comment by deep-gaurav** [comment]
Thanx for the effort. That error is not related though,. It's produced when Media player is not playing and notification broadcast function tries to get current time of media player. It should not cause any problem

**Comment by deep-gaurav** [comment]
I think most of them are fixed in new versions and main topic seems a bit vague, if encountered again open another specific issue, Thankx
