### ISSUE TITLE
[Feature Request] Playlist / Search

### ISSUE THREAD

**Issue by Sok00** [deep-gaurav/MusicPiped#60]
Hello, thanks for the nice app.
I have a feature request. Will it be possible to play the playlist from YouTube? In the results of the search, it would be helpful to know the play length, Views and Author.

Thank you for your wonderful work :)

**Comment by deep-gaurav** [comment]
It's currently possible to import a YouTube playlist, go to 4th tab and open floating action button, the import playlist option will show a popup. You can paste YouTube playlist link in it to import it all

**Comment by deep-gaurav** [comment]
More details are planned and is open issue in #28 closing since duplicate.

**Comment by Sok00** [comment]
The playlist loading animation shows the percent "wrong" ^^
Like: 7.00000000000000% or 23.99999999999999%

Kann ich die Playlist auch mit dem "Teilen" Button

**Comment by deep-gaurav** [comment]
That percentage is not actually wrong it shows video imported / total playlist videos


And you can you share button to copy link to clipboard from YouTube
