### ISSUE TITLE
Forget track

### ISSUE THREAD

**Issue by NickAcPT** [deep-gaurav/MusicPiped#61]
This is a feature request for a way to "forget" tracks are remove the from the cache, music queue and last added list.

**Comment by deep-gaurav** [comment]
Can't you already? Just swipe track left in track list and it'll give delete option?

**Comment by NickAcPT** [comment]
Oh yeah. I can confirm it. Closing this issue.

**Comment by deep-gaurav** [comment]
There are a few more options on swiping right just in case you missed✌
