### ISSUE TITLE
Playback doesn't pause during phone call

### ISSUE THREAD

**Issue by pietrasagh** [deep-gaurav/MusicPiped#65]
Playback doesn't pause during phone call. It's muted during ringtone but during call music is playing and its hard to pause manually.

**Comment by deep-gaurav** [comment]
It was supposedly fixed in recent releases, can you confirm your version?

**Comment by pietrasagh** [comment]
Hi,

I just notticedc and installed update from f-droid. I will test updated
version 1.1 and let you know.

Z poważaniem
Piotr Kowalik

śr., 27 mar 2019, 12:38 użytkownik Deep Gaurav <notifications@github.com>
napisał:

**Comment by pietrasagh** [comment]
On ver 1.1 playback pause during phone call. It doesn't resume
automatically after finished call but that's OK for me. You can
ignore/close my issue.

Great app by the way. Thank you for it.

Z poważaniem
Piotr Kowalik

śr., 27 mar 2019, 12:42 użytkownik Piotr <pietrasagh@gmail.com> napisał:

**Comment by davidhedlund** [comment]
https://github.com/deep-gaurav/MusicPiped/issues/81
