### ISSUE TITLE
App closes when the sleep timer stopped

### ISSUE THREAD

**Issue by cckole** [deep-gaurav/MusicPiped#66]
## Describe the bug
while playing one of the songs I streamed from you tube, I set a sleep timer to trip off the music at a set time. Immediately the sleep timer finish counting and stops the music, the app closes. 

## Steps to reproduce the behaviour

After launching getting into the app 

1. Stream a song from YouTube by typing the title in the search box on the home page of the app.
2. After locating the song on youtube, click on it. It will be converted to audio and store it in the app.
3. play the song
4. On the home page, click on the play list icon by the lower right side at the extreme end.
5. click on the an arrow by the lower left to pop a page where the music can be controlled. 
6. By the top right side, you will see a plus sign in a circle. click on it.
7. It will show a clock where you can set your sleep timer.  Set a desired time to sleep the music and click the OK button.
8. Wait for the time to elapse and watch the app close.

## Expected behaviour
My expectation was that the sleep timer would only stop the music i was playing when the time elapses, and not both the music and the app .

## Video capture of the behaviour

https://youtu.be/1xeb8HABtkI

## Devices and Versions
Techno Spark K7
Android 7.0

**Comment by deep-gaurav** [comment]
Thanks for reporting but I do not understand the but here.
Is not this the expected behaviour?
 From what I know sleep timer is supposed to close app after the specified time, this is how I designed it.

**Comment by cckole** [comment]
Thank you for the response. Actually, all the music players I've used (eg. AB music player and more) only stops the music. As you've mentioned, that the design was intentional, I see nothing bad in that. That's another concept. It isn't mandatory you set yours the same way others made theirs. The only thing you should have done is to make the app display something like this..... "Music stops and app closes at the end of sleep timer" That way, users will understand it isn't a bug. This is the first time I'm coming across a sleep timer with this behavior, that's why I thought it was a bug. I love the app. It made me stream all the songs I've missed in the 90s.... Good job.

**Comment by deep-gaurav** [comment]
App does require quite a bit of documentation and FAQ it'll be done soon, closing this issue as it'll be handled in it
