### ISSUE TITLE
[Bug] This character -> '  isn't displayed correctly on lyrics

### ISSUE THREAD

**Issue by ArmeF97** [deep-gaurav/MusicPiped#67]
![immagine](https://user-images.githubusercontent.com/6240983/56092080-ac0bee80-5eb7-11e9-96a9-d9419d1026bd.png)

This character -> `'`  isn't displayed correctly on lyrics

**Comment by deep-gaurav** [comment]
Oh that's my bad. I forgot to specify unicode encoding., Will be fixed in next version

**Comment by ArmeF97** [comment]
Thanks

**Comment by deep-gaurav** [comment]
Should be fixed in latest release V1.1.4
