### ISSUE TITLE
Add Privacy policy.

### ISSUE THREAD

**Issue by HarryHeights** [deep-gaurav/MusicPiped#69]
Hi, I'm Harry. I was curious about how you deal with users privacy when the software is utilized. It'd be a nice addition to the project. And I could help you create the document.

**Comment by deep-gaurav** [comment]
Hi that would be helpful.

I can provide you insigh of what privacy related actions app does.

Currently the app does not collect any kind of data from user but does makes use of 2 APIs
- Google search API for getting search suggestion
- Invidious API for fetching video details, Invidious API is open source and should not collect any data either.

But google might collect search data, although no private information is send to indicate the user who is searching except IP.

**Comment by HarryHeights** [comment]
Oh okay! Thanks for the information. With it, I'd be able to create the privacy policy statement. I'll get to work and send a PR.

**Comment by deep-gaurav** [comment]
closing it as done in #72
