### ISSUE TITLE
[Feature request] Refresh and delete options for playlists

### ISSUE THREAD

**Issue by mario-g98** [deep-gaurav/MusicPiped#70]
It will be wonderful if there is the abillity to:
  - remove playlists
  - refresh already added playlists

**Comment by deep-gaurav** [comment]
I'm not sure what refresh playlist means but playlist can be removed already by swiping right

**Comment by mario-g98** [comment]
I have a custom playlist in YouTube, in which I add my favourite songs and I just imported it in MusicPiped. Now when I go in YouTube and add/remove a song, I want to be able to get back to MusicPiped, hit Refresh and update the playlist.. or maybe swipe down to refresh like in Google Chrome :)

**Comment by deep-gaurav** [comment]
Current implementation of playlist doesn't save id of playlist so refreshing is not possible, implementation will need some database change, therefore will add in later version and not priority.

**Comment by deep-gaurav** [comment]
Playlist will automatically sync if imported from YouTube from version v2.0.1, so i think it's now implemented, closing issue
