### ISSUE TITLE
Media controls not considered

### ISSUE THREAD

**Issue by PeterHindes** [deep-gaurav/MusicPiped#73]
Media controls from bluetooth headphones are not used by the app and ignored.

**Comment by deep-gaurav** [comment]
Yea, currently a MediaPlayer is used to play music and all controls to it are custom. It does not receive any system wide broadcast which can be implemented

**Comment by deep-gaurav** [comment]
Implementing bluetooth/ any system audio control can be done by receiving proper broadcast and calling setting proper playerstate and pausing/playing mediaplayer

see from line 608 of PlayerService
https://github.com/deep-gaurav/MusicPiped/blob/ddff3f585191e91702c47e69904bc2679dccfffe/android/app/src/main/java/me/devsilver/musicpiped/PlayerService.java#L608

**Comment by deep-gaurav** [comment]
Hi, with v2.0.1 media buttons/controls should work. closing issue
