### ISSUE TITLE
Donation Feasible?

### ISSUE THREAD

**Issue by deep-gaurav** [deep-gaurav/MusicPiped#76]
This is a discussion thread.
I was wondering If this app is worth Donating to?
i.e Should I add a donation link, I might be able to invest more time in app then currently am and fix bugs quickly/add more features. Or is app not important enough to donate to.
And if donation is possible Should I add a one time donation (Paypal/buymeacoffee) like or recurring liberapay/patreon like.

I would love to hear anything on the topic.
Thanks

**Comment by Norde** [comment]
From my point of view, any useful application (big or small) deserves donation.

Donations are only on voluntary basis, thus everyone is free to choose.
So there is no harm in including this.


For the donation format it depends on your objectives concerning the application (future development, etc ...).
IMHO i would say that a one-time donation seems the best choice for now.

**Comment by deep-gaurav** [comment]
Thanks for response @Norde

I do plan to continue developing/supporting this app for quite long. 
Currently I don't really have a physical testing device (my current phone is quite old doesn't connect to PC) and flutter's debug and release versions differ quite a bit thus AVD doesn't exactly represent exactly how app would behave when released. This has made fixing and even identifying quite a lot of bugs difficult (still many open issue).

And since there is no analytics in app, it is hard to know if there is enough userbase to consider investing in something to help with development of this app.

**Comment by HarryHeights** [comment]
This app is very valuable to me. I would love to see continuous development. To that end, prompting donations isn't a bad idea at all.  Like @Norde  said, donations are on a voluntary basis.  Again, I agree with @Norde that a one-time donation is the best choice.

**Comment by deep-gaurav** [comment]
Thank you for opinion @HarryHeights
There are some changes and new features on way in few days, and plan to redo  Readme with it since it doesn't represent app very well(even screenshots), I'll add donation links with it

**Comment by HarryHeights** [comment]
That's great 👍🏽

**Comment by Norde** [comment]
You can also set a specific goal to your donation plan (like a new phone, for the reasons you explained above).

With the appropriate explanations I'm sure people will understand =)

**Comment by deep-gaurav** [comment]
Major changes are done in v1.2.0 will redo README and add links, thanks for all your feedback, appreciate it all :)
