### ISSUE TITLE
[Feature Request] Copy Links

### ISSUE THREAD

**Issue by psxws** [deep-gaurav/MusicPiped#78]
Maybe I'm missing the obvious but I don't see a way to do this currently. Would be nice to have an easy way to copy the youtube URL of the song currently playing to the clipboard.

I like to share what I'm listening to sometimes & it's kind of a pain to have to go into YouTube for the link .

**Comment by deep-gaurav** [comment]
I keep forgetting to add it, thanks for issue, will be done in next release

**Comment by deep-gaurav** [comment]
Done in v1.2.0, closing issue
