### ISSUE TITLE
Playback doesn't pause if headphones disconnect

### ISSUE THREAD

**Issue by davidhedlund** [deep-gaurav/MusicPiped#81]
Please implement pause when headphones (wired or Bluetooth) are disconnected. An option to auto-start the last station on connect would be nice too, if possible, but not as important.

**Comment by davidhedlund** [comment]
https://github.com/ram-on/SkyTube/issues/435

**Comment by davidhedlund** [comment]
https://github.com/segler-alex/RadioDroid/issues/22

**Comment by davidhedlund** [comment]
https://github.com/deep-gaurav/MusicPiped/issues/65

**Comment by deep-gaurav** [comment]
This and #73 are related and will be implemented in next version

**Comment by davidhedlund** [comment]
@deep-gaurav Alright, thank you in advance.

**Comment by deep-gaurav** [comment]
Hi, this is finally implemented in v2.0.1, closing issue

**Comment by davidhedlund** [comment]
> Hi, this is finally implemented in v2.0.1

Thanks!
