### ISSUE TITLE
Feature request: Make it possible to download playlists links from text files

### ISSUE THREAD

**Issue by davidhedlund** [deep-gaurav/MusicPiped#83]
I got a plain text file, each line has a pure YouTube playlist link. I'd love to download all of them in MusicPiped but there's no option to do so. What do you think about the idea?

**Comment by davidhedlund** [comment]
https://github.com/deep-gaurav/MusicPiped/issues/82

**Comment by deep-gaurav** [comment]
That is a very specific kind of request.

I'm planning on adding import/export playlist #43
The export format will be simple JSON most likely
Once it's done you should be able to format your links file like the exported JSON and import it

**Comment by davidhedlund** [comment]
> That is a very specific kind of request.
> 
> I'm planning on adding import/export playlist #43
> The export format will be simple JSON most likely
> Once it's done you should be able to format your links file like the exported JSON and import it

JSON is even better. Can you please mention JSON on https://github.com/deep-gaurav/MusicPiped/issues/43 ?
