### ISSUE TITLE
Import playlist feature is not working for MusicPiped app version 1.1.5

### ISSUE THREAD

**Issue by chrisbarth01** [deep-gaurav/MusicPiped#85]
**Expected behavior**
- I expected the app to import my YouTube playlist when I input my link and click on the import option.

---

**Actual behavior**
- The app doesn't import my YouTube playlist; it just stays at 0.0%

---

**How to reproduce**
- Download, install and launch the latest version of the app
- Click on the playlist option at the down right corner of the screen 
- Click on the three vertically arranged dots 
- Select 'import playlist'
- Input a valid YouTube playlist link
- Wait for as long as you can
- See error

---

- App Version: v1.1.5
- Device: Gionee f100s 
- Operating System: 6.0

---

**Recording of the bug**

https://youtu.be/enTFnc2DFsQ

**Comment by deep-gaurav** [comment]
`?list=WL` is watch later playlist and is private for your account, it cant be accessed by app. you can only import shareable playlists

**Comment by chrisbarth01** [comment]
Share able playlist like?

**Comment by deep-gaurav** [comment]
No, that playlist does not open either, 
Easiest way to test if playlist is I portable is open link in incognito mode in browser if it opens, it should import

**Comment by chrisbarth01** [comment]
OK....

**Comment by chrisbarth01** [comment]
I love your app and I promoted it as much as I could [here](https://partiko.app/chrisbarth/musicpiped-the-no1-music-streaming-app-that-streams-music-from-youtube-f44c84f4fa969?referrer=chrisbarth)
