### ISSUE TITLE
Notification Area - No Music Controls

### ISSUE THREAD

**Issue by LeonSandler** [deep-gaurav/MusicPiped#86]
I tried using the app from F-Droid and Google Play but I don't have control music in notification in any of them.

Tried clearing all data and reinstalling the app - No success, still nothing.
Tried restarting - Also nothing.
Notifications are not blocked.

I am running Xiaomi mi mix stock.

See attached gif for reference:

![Gif piped](https://user-images.githubusercontent.com/35928032/57197234-972df280-6f6d-11e9-8909-e64c509a65de.gif)

**Comment by deep-gaurav** [comment]
Can you retry with v2.0.1 I think it's fixed

**Comment by LeonSandler** [comment]
Fixed. Nice job.
