### ISSUE TITLE
MusicPiped LineageOS Equalizer Issue

### ISSUE THREAD

**Issue by linuxhelper** [deep-gaurav/MusicPiped#89]
MusicPiped continues to crash at launch in LineageOS. App works again for a few weeks or so after OS upgrade - but crash behavior reappears. Tried clearing cache & data for MusicPiped & AudioFX equalizer. Turned equalizer off - but no option to disable under app info.

/////////// java.lang.RuntimeException: Unable to create service me.devsilver.musicpiped.PlayerService: java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3 at android.app.ActivityThread.handleCreateService(ActivityThread.java:3349) at android.app.ActivityThread.-wrap4(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6494) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) Caused by: java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3 at android.media.audiofx.AudioEffect.(AudioEffect.java:411) at android.media.audiofx.Equalizer.(Equalizer.java:139) at me.devsilver.musicpiped.PlayerService.onCreate(PlayerService.java:174) at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339) ... 8 more

**Comment by linuxhelper** [comment]
https://github.com/deep-gaurav/MusicPiped/issues/75

**Comment by deep-gaurav** [comment]
Equalizer has now been removed in v2.0.1 so closing issue
