### ISSUE TITLE
Queue does not update when track is changing

### ISSUE THREAD

**Issue by mpiffault** [deep-gaurav/MusicPiped#91]
Reproducing :
Launch a playlist
Access to track details
Access to Queue details with top right icon

What is expected :
When track change at the end of the current track, the queue is updated accordingly

What is happening :
The play icon stays on the track played at the moment I accessed the queue, and thes indices does not update either.

**Comment by deep-gaurav** [comment]
That is known,. Currently queue is generated when it's opened and so is not updated closing and opening it again should update. It'll be fixed in later release

**Comment by deep-gaurav** [comment]
It's fixed in v2.0.1, closing issue
