### ISSUE TITLE
Red Error Screen

### ISSUE THREAD

**Issue by mario-g98** [deep-gaurav/MusicPiped#92]
Sometimes after a song ends I get this screen and I need to restart the app.

![Screenshot_20190522-124158](https://user-images.githubusercontent.com/49582442/58169262-9ea10b80-7c90-11e9-8360-3536ab75c517.jpg)

**Comment by 2secslater** [comment]
Can confirm here also. Although, after a period of time, it disappears and beings playing the next track in queue as normal. It also sometimes appears briefly when skipping tracks.

My device is a Huawei LDN-L01 (Huawei Y7 2018).

**Comment by deep-gaurav** [comment]
The bug should be fixed in v2.0.1 update, Closing issue
