### ISSUE TITLE
Allow to use custom Invidious server

### ISSUE THREAD

**Issue by dimqua** [deep-gaurav/MusicPiped#96]
It's not possible to specify your own Invidious server, you can only select from the list of predefined ones.

**Comment by deep-gaurav** [comment]
Hi, I would like to temporarily redirect you to web version, it's more features including this and is more stable.
https://deep-gaurav.github.io

**Comment by deep-gaurav** [comment]
@dimqua from v2.0.1 you can type in your custom invidious link, closing issue
