### ISSUE TITLE
 [Feature Request] Search for playlist

### ISSUE THREAD

**Issue by nicolas-raoul** [deep-gaurav/MusicPiped#99]
Searching for a playlist should be doable from within the app.

Currently the flow is very sub-optimal:
1. Exit the app
2. Launch browser
3. Search for playlist in browser
4. Copy the URL
5. Come back to MusicPiped
6. Paste the URL

**Comment by deep-gaurav** [comment]
Search is now enhanced in v2.0.5 you can now search video, channel/artist and playlist all and import/ play playlist directly
